### ISSUE TITLE
Resultado "installmentsInsterestRate" não está retornando no JSON

### ISSUE THREAD

**Issue by zeluizr** [vtex/vtex.js#12]
Havia uma linha no JSON que era: **installmentsInsterestRate**, que usava para fazer o rating da página, porém ele foi removido! Alguém pode me ajudar com isso, tem outro lugar que eu retorno o rating do produto?

**Comment by brenoc** [comment]
@zeluizr installmentsInterestRate se refere a taxa de juros do parcelamento de um produto. Qual chamada que parou de vir esse dado?

**Comment by zeluizr** [comment]
@brenoc, o campo que preciso é de rating de produtos.

**Comment by brenoc** [comment]
@zeluizr você sabe dizer qual API que fornece esses dados?

**Comment by zeluizr** [comment]
No vtex.js (http://lab.vtex.com/docs/vtex.js/lib/latest/catalog/index.html) e no search (http://lab.vtex.com/docs/search/api/beta/search/index.html)

**Comment by brenoc** [comment]
@zeluizr, conversei com o pessoal do catálogo e infelizmente não existe API pública para o rating dos produtos. Essa informação só pode ser pega através dos controles ou através de APIs privadas, que não é o caso do vtex.js.

**Comment by zeluizr** [comment]
@brenoc, muito obrigado... 
Uma pequena observação... pelos controles de produto, está vindo com erro os dados.
Abrs.,

**Comment by brenoc** [comment]
@zeluizr abre um chamado com o cenário pros desenvolvedores responsáveis darem uma olhada nisso!  Abs!
