### ISSUE TITLE
O método  vtexjs.checkout.getOrderForm não trás dados atualizados

### ISSUE THREAD

**Issue by caljp13** [vtex/vtex.js#14]
Quando eu executo o método 
```vtexjs.checkout.getOrderForm(["items","totalizers","shippingData"])``` ele faz a requisição $.ajax e traz os dados do checkout. OK.

Porém se executo uma segunda vez na tela ele não faz a requisição e usa os dados "cacheados" no 
```vtexjs.checkout.getOrderForm``` e não me traz os dados de um produto recentemente adicionado por exemplo.

**Comment by brenoc** [comment]
Oi, @caljp13, se você adicionou o produto sem usar o vtex.js isso deve acontecer mesmo. A ideia é que ele centralize todas as chamadas com relação ao carrinho, se isso é feito, o orderForm estará sempre atualizado.

**Comment by caljp13** [comment]
@brenoc entendi. Caso eu queira add o produto por fora do vtex.js existe alguma forma de obter os dados atualizados? Algum método?

**Comment by brenoc** [comment]
Não, nesse caso você teria que fazer a chamada que o proprio vtex.js faz. Que é um POST para `/api/checkout/pub/orderForm` com `{"expectedOrderFormSections":["items","totalizers","clientProfileData","shippingData","paymentData","sellers","messages","marketingData","clientPreferencesData","storePreferencesData","giftRegistryData","ratesAndBenefitsData","openTextField"]}` como data.
