### ISSUE TITLE
simulateShipping descontinuado

### ISSUE THREAD

**Issue by felipe-ssilva** [vtex/vtex.js#51]
Com o **simulateShipping** descontinuado, qual seria a alternativa para o mesmo?

**Comment by njfajardo** [comment]
Puede usar directamente el api de vtex para hacer la simulación:
`function getSla(id, zipCode) {
    var DataToSend = {
        'items': [{
            'id': id,
            'quantity': 1,
            'seller': '1'
        }],
        'postalCode': zipCode,
        'country': 'ARG',
    };

    $.ajax({
        'type': 'POST',
        'dataType': 'json',
        'contentType': 'application/json',
        'url': '/api/checkout/pub/orderForms/simulation/?sc=1',
        'data': JSON.stringify(DataToSend),
        'success': function(ResponseData) {
           `//CUSTOM` function
            createTable(ResponseData)
        },
        'error': function(AjaxError) {
            console.log('Error')
        }
    });
}`

**Comment by felipe-ssilva** [comment]
Tks @njfajardo

**Comment by andredalmolin** [comment]
Felipe, você pode editar a biblioteca e depois fazer um PR. Assim todos saem ganhando.
