### ISSUE TITLE
Implementar e documentar addToCart

### ISSUE THREAD

**Issue by firstdoit** [vtex/vtex.js#6]
&redirect=false

@marcelocouto também tem que devolver com redirect = false nas suas APIs

**Comment by brenoc** [comment]
:+1: Pull requests da comunidade são bem vindos!

Consiste basicamente em criar uma função no módulo Checkout chamada `addToCart`, que receba os mesmos parâmetros da chamada `/checkout/cart/add?sku=2000017830&qty=1&seller=1&redirect=true&sc=1`. Documentar e criar testes para a função.

**Comment by brenoc** [comment]
O teste deve verificar a URL e os parâmetros que estão sendo enviados.

**Comment by tamorim** [comment]
Pull request criado: vtex/vtex.js#11
