### ISSUE TITLE
Retornar serviço associado ao SKU no módulo Catalog

### ISSUE THREAD

**Issue by josantana** [vtex/vtex.js#7]
Pessoal,

Existe a possibilidade de retornar os dados de um serviço (como garantia estendida) associado ao SKU de um produto? Por exemplo:
```
skus: [
  0: {
    available: true,
    sku: 93649,
    installments: 12,
    service: {
      sku: 26139,
      name: 'Garantia Estendida',
      price: 109.90,
      installmentValue: 9.16,
    },
    ...
  }
]
```
Atualmente só tenho essa informação através da viewpart "stockKeepingUnitService".

**Comment by brenoc** [comment]
@josantana :+1: seria uma boa mesmo, vou avaliar a possibilidade da API expor essa informação

**Comment by brenoc** [comment]
Sera resolvido em vtex/vtex.js#8
